d={}
K1=(input("enter first language"))
K2=(input("enter second language"))
K3=(input("enter third language"))
K4=(input("enter fourth language"))
n1=input("enter your name")
n2=input("enter your name")
n3=input("enter your name")
n4=input("enter your name")
d[n1]=[K1]
d[n2]=[K2]
d[n3]=[K3]
d[n4]=[K4]
print(d)#IF 2 FRIENDS NAMES ARE ENTERED SAME THEN THE VALUE OF THE 2ND ONE WILL BE CONSIDERED AND NAME WILL BE PRINTED ONLY ONCE